### ISSUE TITLE
hi，parthe， the project miss some document 

### ISSUE THREAD

**Issue by cccse4** [parthe/Speaker-Diarization-toolkit-MATLAB#1]
the project at least miss the documents:
getmfcc.m
gmm_em.m

i install the voicebox tools and any other tools ，but it still doesn't run smoothly.
can you provide all codes for me? thanks

best
Tuo
my email :   sa514025@mail.ustc.edu.cn

**Comment by parthe** [comment]
1. I shall add the missing files soon. I am still to conduct extensive testing of the toolkit. Watch this repo. I will add the codes by the weekend.
2. gmm_em is a function in the MSR speaker recognition toolkit

**Comment by cccse4** [comment]
Your codes have important reference value for the students in this professional field.Thank you for  your help. Looking forward to learn all codes.
Best

**Comment by parthe** [comment]
Thanks cccse4
I personally had to struggle a lot to build a system during my masters thesis. This is an attempt to make speaker diarization research faster for students entering the field by getting rid of the activation energy.

I will do my best to keep this updated

**Comment by cccse4** [comment]
hi parthe
1.Because the project don't have the funtion of getmfcc.I make mfcc  by myself，but the effect of remove_silence is bad. I think the config of MFCC is different.can you provide the function of getmfcc?
2. Which papars are the reference of remove_silence and SAD?Can you recommend me about the paper?thanks

3.What is the meaning of them? which papers should I read？
[~,Msp] = evalc('GMM_matlab2cluster(GMM_MSR2matlab(gmm_em({transpose(sp)},nG.snG,10,1,12)))');
[~,Mnsp] = evalc('GMM_matlab2cluster(GMM_MSR2matlab(gmm_em({transpose(nsp)},nG.nnG,10,1,12)))')

**Comment by cccse4** [comment]
hi parthe,
1. Have a nice Thanksgiving Thanksgiving wishes for you and your family.
2. can you provide the function of getmfcc? the project don't have the funtion of getmfcc.
3. How can I train the timit ubm? I have the timit database.
4. can you provide some references about the project,?

Thank you.Looking forward to waiting for this updated.

**Comment by parthe** [comment]
Hi,

I have changed the code for extract_MFCC. However there has been a folder restructuring also. You may have to pull again. :-/
Also, Data files have been provided now. Check out the UBM for the TIMIT data and the corresponding T-matrix and WCCN matrix for the TIMIT data

The best reference for this toolkit would be my Thesis. The link is given below
http://www.slideshare.net/ParthePandit/parthepandit10d070009ddpthesis-53767213
Training UBM can be done using the functions in the MSR_Identity toolkit

**Comment by cccse4** [comment]
Hi,parthe
Please extend my thanks, on behalf of all of my classmates, to you.The system make us learn the technology of speaker diarization easier.Hope to have the opportunity to ask you some views on this technology.

best wishes
Tuo

**Comment by parthe** [comment]
Your welcome.
